### ISSUE TITLE
Having multiple rules on one line breaks highlighting

### ISSUE THREAD

**Issue by blackrobot** [groenewege/vim-less#10]
If I have multiple Less or CSS rules on the same line, it breaks highlighting. For instance:

``` CSS
#container {
    background: #000; color: #fff;
}
```

Will cause background to be highlighted correctly, as well as `#000` but everything else on the line appears in blue.
