### ISSUE TITLE
Nested a:hover

### ISSUE THREAD

**Issue by solispauwels** [groenewege/vim-less#30]
``` css
.rule {
    a:hover {
        color:#fff;
    }
}
```

have different hightlighting then:

``` css
.rule {
    a:hover
    {
        color:#fff;
    }
}
```
