### ISSUE TITLE
Wrong indentation with nested properties

### ISSUE THREAD

**Issue by antoinemenini** [groenewege/vim-less#31]
I'm using vim-less vim bundle to autoindent my .less files in vim. The problem is that it doesn't work properly on nested properties:

When I autoindent my code I get this:

``` css
#header{
  margin: 0;
  div{
    display: inline;
    a{
      text-decoration: none;
}
}
span{
  color: #ffffff;
}
}
```

instead of :

``` css
#header{
  margin: 0;
  div{
    display: inline;
    a{
      text-decoration: none;
    }
  }
  span{
    color: #ffffff;
  }
}
```

Here is my ~/.vimrc :

```
set nocompatible

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

"Highlight Tabs and Spaces
set expandtab
set smarttab
set nocompatible
set hlsearch

" autoindent
filetype on
filetype plugin on
filetype indent on

" Show line number
:set number

syntax enable
set shiftwidth=2
set expandtab
set softtabstop=2

" https://github.com/tpope/vim-pathogen
execute pathogen#infect()
```

The only vim bundle that I'm using is the vim-less bundle.
