### ISSUE TITLE
Bad Indention

### ISSUE THREAD

**Issue by bayleedev** [groenewege/vim-less#33]
There seems to be an issue with indention. This is the simplest example I could come up with. I have this formatted LESS:

``` less
td > table.sub {
    width: 100%;
    * {
        padding: 0;
    }
}
```

Formatting with `=` causes:

```
td > table.sub {
    width: 100%;
           * {
               padding: 0;
           }
       }
```
