### ISSUE TITLE
Folding issue with nested rules on same line

### ISSUE THREAD

**Issue by zanona** [groenewege/vim-less#49]
Apparently having the following rule structure, causes the code folding to break.

```less
ul {
    li { display: block; padding: .5em; a { color: red; } } 
    h4 { color: red; }
} 
```

folded looks like:
```less
+ul {...li { display: block; padding: .5em; a { color: red; } }                                    
    h4 { color: red; }
} 
```

the only way to grant the code-folding will be correct is to split nested rules into different lines such as:

```less
ul {
    li { display: block; padding: .5em;
        a { color: red; }
    } 
    h4 { color: red; }
} 
```
which properly folds to

```less
+ul {...} 
```

**Comment by dhruvasagar** [comment]
Well to be honest, it should really be written as : 

```less
ul {
  li {
    display: block;
    padding: .5em;
    a {
      color: red;
    }
  }
  h4 { color: red; }
}
```
